/** Limiares de presença — Controle de Acessos (centralizado). */
export const ACCESS_PRESENCE = {
  ONLINE_MS: 2 * 60 * 1000,
  INATIVO_MS: 10 * 60 * 1000,
};

export const ACCESS_HEARTBEAT_MS = 45_000;

export const ACCESS_SESSION_KEY = "pp_access_session_token";

export const ACCESS_EVENT = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  LOGIN_DENIED: "LOGIN_DENIED",
  SESSION_TIMEOUT: "SESSION_TIMEOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  DEVICE_CHANGED: "DEVICE_CHANGED",
  UNUSUAL_HOUR: "UNUSUAL_HOUR",
  UNUSUAL_LOCATION: "UNUSUAL_LOCATION",
  ADMIN_SESSION_TERMINATED: "ADMIN_SESSION_TERMINATED",
};

/** Tipos exibidos na aba Segurança. */
export const ACCESS_SECURITY_TYPES = [
  ACCESS_EVENT.LOGIN_DENIED,
  ACCESS_EVENT.SESSION_EXPIRED,
  ACCESS_EVENT.SESSION_TIMEOUT,
  ACCESS_EVENT.PASSWORD_CHANGED,
  ACCESS_EVENT.DEVICE_CHANGED,
  ACCESS_EVENT.UNUSUAL_HOUR,
  ACCESS_EVENT.UNUSUAL_LOCATION,
  ACCESS_EVENT.ADMIN_SESSION_TERMINATED,
];

/** Alertas “ao vivo” (banner) — novo dispositivo / horário / localização. */
export const ACCESS_ALERT_TYPES = [
  ACCESS_EVENT.DEVICE_CHANGED,
  ACCESS_EVENT.UNUSUAL_HOUR,
  ACCESS_EVENT.UNUSUAL_LOCATION,
];

const ROTULOS_EVENTO = {
  [ACCESS_EVENT.LOGIN]: "Login",
  [ACCESS_EVENT.LOGOUT]: "Logout",
  [ACCESS_EVENT.SESSION_EXPIRED]: "Sessão expirada",
  [ACCESS_EVENT.LOGIN_DENIED]: "Acesso negado",
  [ACCESS_EVENT.SESSION_TIMEOUT]: "Timeout por inatividade",
  [ACCESS_EVENT.PASSWORD_CHANGED]: "Senha alterada",
  [ACCESS_EVENT.DEVICE_CHANGED]: "Novo dispositivo",
  [ACCESS_EVENT.UNUSUAL_HOUR]: "Horário incomum",
  [ACCESS_EVENT.UNUSUAL_LOCATION]: "Localização incomum",
  [ACCESS_EVENT.ADMIN_SESSION_TERMINATED]: "Encerrada por admin",
};

export function rotuloEventoAcesso(tipo) {
  return ROTULOS_EVENTO[tipo] || tipo || "—";
}
