/** Limiares de presença — Controle de Acessos (centralizado). */
export const ACCESS_PRESENCE = {
  ONLINE_MS: 2 * 60 * 1000,
  INATIVO_MS: 10 * 60 * 1000,
};

export const ACCESS_HEARTBEAT_MS = 45_000;

export const ACCESS_SESSION_KEY = "pp_access_session_token";

export const ACCESS_EVENT = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  LOGIN_DENIED: "LOGIN_DENIED",
  SESSION_TIMEOUT: "SESSION_TIMEOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  DEVICE_CHANGED: "DEVICE_CHANGED",
  ADMIN_SESSION_TERMINATED: "ADMIN_SESSION_TERMINATED",
};

export const ACCESS_SECURITY_TYPES = [
  ACCESS_EVENT.LOGIN_DENIED,
  ACCESS_EVENT.SESSION_EXPIRED,
  ACCESS_EVENT.SESSION_TIMEOUT,
  ACCESS_EVENT.PASSWORD_CHANGED,
  ACCESS_EVENT.DEVICE_CHANGED,
  ACCESS_EVENT.ADMIN_SESSION_TERMINATED,
];
